vkconfig: Add support for VK_KHR_portability_subset to devsim
LunarG/VulkanTools pull request #1165
Opened 2020-09-16 16:28 UTC by christophe-lunarg

- Add a setting to be able to enable VK_KHR_portability_subset emulation with devsim
- Sort the layers in a matter that reflect the layer properties. devsim layer will always be ordered last, close to the device.

TODO:
- Check the version of devsim layer before displaying VK_KHR_portability_subset emulation setting.
- Show warning when the user doesn't exclude or override the validation layer when adding the devsim laye

2020-09-16 22:18 UTC, richard-lunarg requested changes
Almost there. None of the settings for the device simulation layer are saved. Even just switching from the active configuration and back clears them all to blank again. I stepped into the settings tree, and the editProfile slot is being called, but then it goes into unfamiliar code (I think you are caching settings somewhere else now). I figured you probably could fix it faster than me figuring it out.

2020-09-17 06:03 UTC, christophe-lunarg commented
Ok, this is a little weird, I'll investigate !

2020-09-17 13:53 UTC, christophe-lunarg commented
@richard-lunarg I fixed this issue with a dedicated PR: #1170 It's actually the display of the setting that was broken. One line fix!

2020-09-17 15:54 UTC, richard-lunarg commented
The json file was also not being saved. I'll double check, but that might still be broken.

2020-09-17 15:56 UTC, richard-lunarg commented
Okay, got to that quicker than I thought. Seems to be fixed.

2020-09-17 15:58 UTC, richard-lunarg approved these changes

2020-09-17 17:48 UTC, jeremyk-lunarg reviewed
On my system VkConfig seems to always turn Portability emulation on.

2020-09-17 22:12 UTC, jeremyk-lunarg reviewed
I'm still getting weird behavior when I test this change with vulkaninfo.

When I set up DevSim in VkConfig and run vulkaninfo, it acts as though portability emulation is always on and adds extra entries to the list of device extensions.

When I set up DevSim manually, everything works as expected.

2020-09-18 08:59 UTC, christophe-lunarg commented
@jeremyk-lunarg the problem was that I didn't rebase master that had this https://github.com/LunarG/VulkanTools/pull/1170 PR which fix the display of "bool_numeric" settings which this setting is.

2020-09-18 08:59 UTC, merged

2020-09-18 16:03 UTC, johnzupin commented
> None of the settings for the device simulation layer are saved. Even just switching from the active configuration and back clears them all to blank again.

I'm seeing this on Linux as well. The .json file is being saved between sessions.

2020-09-18 16:19 UTC, johnzupin commented
I'm not seeing the portability extension always being on when using vkconfig

2020-09-18 16:41 UTC, johnzupin commented
> >    None of the settings for the device simulation layer are saved. Even just switching from the active configuration and back 
> > clears them all to blank again.

> I'm seeing this on Linux as well. The .json file is being saved between sessions.

Please ignore this comment. Pulled in master and this looks good! Setting are being saved.